version: "3.8"

services: 
  nginx-container:
  image: nginx:1.23
  container_name: nginx-container
  networks:
    - metrics
    - internal-website
  volumes:
    - ./nginx:/usr/share/nginx/html
    - ./stub.conf:/etc/nginx/conf.d/stub.conf
  ports:
    - '8080:80'

networks: 
  metrics:
    external: true
  internal-website: